export const successMessage = {
  DEPARTMENT_CREATED: "Department created successfully",
  DEPARTMENT_UPDATED: "Department updated successfully",
  DEPARTMENT_DELETED: "Department deleted successfully",
  PROJECT_CREATED: "Project created successfully",
  USER_CREATED: "User created successfully",
  DATA_FETCHED: "Data fetched successfully",
  BOARD_STATUS_CREATED: "BoardStatus created successfully",
  BOARD_STATUS_UPDATED: "BoardStatus updated successfully",
  BOARD_STATUS_DELETED: "BoardStatus deleted successfully",
  PROJECT_UPDATED: "Project updated successfully",
  PROJECT_DELETED: "Project deleted successfully",
  OTP_SENT: "OTP sent to your registered email.",
  OTP_VERIFIED: "OTP verified successfully",
  PASSWORD_CHANGED: "Password changed successfully",
};
